language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.1
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
jdk:
   - oraclejdk8

before_install:
   - pip install --user codecov

script:
   - travis_wait ./gradlew clean plex-rest-library:jacocoTestReport jacocoTestReportDebug sonarqube
   
after_success:
  - codecov

sudo: false
